// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#pragma kernel CSMain2

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
//RWTexture2D<float4> Result;
RWStructuredBuffer<int> Result;
int hoge;

[numthreads(8,8,1)]
void CSMain (int3 id : SV_DispatchThreadID)
{
	// TODO: insert actual code here!

	//Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);

	Result[id.x + 8*id.y] = id.x + 8*id.y;
}

[numthreads(8,8,1)]
void CSMain2(int3 id : SV_DispatchThreadID) {
	Result[id.x + 8 * id.y] = id.x + 8 * id.y + hoge;
}
